name: CI

on:
    push:
        branches: [master, actions]
    pull_request:
        branches: [master, actions]

jobs:
    setup:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [2.7, 3.6, 3.7, 3.8]

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                python-version: ${{ matrix.python-version }}

            - name: Install system dependencies
              run: |
                sudo apt-get update -y
                sudo apt install libcurl4-openssl-dev libssl-dev
                sudo apt-get install libgnutls28-dev

            - name: Install python dependencies
              run: |
                pip install --upgrade pip setuptools py
                pip install twine wheel coveralls
                pip install -e .[all]

            - name: Run pytest tests
              run: ./run-tests.sh
            
            - name: Codecov Coverage
              if: matrix.python-version == 3.8
              uses: codecov/codecov-action@v1
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                files: coverage.xml
